// <auto-generated />
using System;
using ControlGastos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlGastos.Infrastructure.Migrations
{
    [DbContext(typeof(ControlGastosDbContext))]
    partial class ControlGastosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ControlGastos.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecurringExpenseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecurringExpenseId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ControlGastos.Domain.Entities.RecurringExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ApproximateAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfPayment")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FixedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RecurringExpenses");
                });

            modelBuilder.Entity("ControlGastos.Domain.Entities.RecurringIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfIncome")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FixedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecurringIncomes");
                });

            modelBuilder.Entity("ControlGastos.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ControlGastos.Domain.Entities.RecurringExpense", "RecurringExpense")
                        .WithMany()
                        .HasForeignKey("RecurringExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecurringExpense");
                });
#pragma warning restore 612, 618
        }
    }
}
